void waitBusy() ;
void sendChar( unsigned char i) ;
void sendInst8( unsigned char i) ;
void sendInst4( unsigned char i) ;
void sendInst(unsigned char byte) ;
void sendChar4(unsigned char i) ;
void gotoXY(unsigned char x, unsigned char y) ;
void writeStringXY(char *txt, unsigned char x, unsigned char y) ;
void writeString(char *txt) ;
void writeString8(char *txt) ;
void writeString4(char *txt) ;
